import type { Metadata } from "next";
import { Space_Mono } from "next/font/google";
import "./globals.css";

const font = Space_Mono({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Campus CoLab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>{children}</body>
    </html>
  );
}
